language: node_js
node_js:
- lts/*
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: LS9VtxOLld52U+t0Vhgg87xCyG/E3toPOmU5F125Ruo5Pkln5fAHw5NiRUYUV/aeONE9ManOQSXDtF/F4MBIx7CuS2Z07GnSd21lzcciWQsU4145xtGxmThhgoOvsE2L6rEnWAJtMtoXo0wsbF5PZN67Vzgt90DHF10n3PtjuNHfSu49Me5YGCITsvCud23DriofdCJGA/CKQWo60438mLyK1DMIwWTKWawRVEGXC4qu+2R0TKsm3Wa6wu6ru6NYxLzUN3kiyxBVGnHBOtBQpFlesg1siSmd2X8LWcxH5FJ9xcf1Gnmr361Gdex7NKYBoIifiQFti/c6i7xJocOuBRI3v0B7rerw7OoRBEQvSxCUpCM3cEWUSAztk8DpmDySYpFYpkGwgKL8r1SoE5EtXRjLxGTvyFtWACyT/bwmcZBVj4U4QLbPqhjV5AQsZWxUZYwXROiFNl0FgGKadpLaBWtg2rRM8KqD+Q+FyRoN2wgZKxid8iBSLYpkPCXCvEkjAMo7iO7Fps86E92w0UWhwsolHnvmIAXJACXh8ZyobON5wsYKsPL3/bnPMp9ShdZmejdnMSWqcXRwZysLGpQtdaYRtF/HUH2HHMKvvh6tK4/VY2gF/76ftLdJywEdByp49A7o2/vsJtRg/U6n3/vo3x0ubOZALpJHs+8lKh2MjwI=
  app: typescript-postgres-docker-example-app
