language: node_js
node_js:
  - lts/*
script:
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: B5n08qYd1xqhIluqOLBhpSX+e4X2uAvoNxJH2X395r6mxUB/bv2w8bcu36bBcpwv2vGoh6l26fdcnZ1yUMZHRtgrBN5bUleCLe5/OxcBylM8loV4JS1jbal8k6Y8Khh23hhKhlMYVT566pzuD+yUExn3ypKmjn10JSfd4uyiE73QmylofKxbazcFp20k8cq892gg6qOQ2B51qkCT7aXtL/7hfj+ZVvP4I44W2VRpEdbDb3XFwRNQl3xHFRUXf4G7Ovlpzbt5bpkxN4EM3wyuSs1twSHjMmrNa2w4bFVqSoZB2HB4y+vcxEE+7oCfVTSnbka+6KzRCUJv3L1YLihsw6+b5BXP0/4uP8b9BSykySIaR5jvEy74R3JUT57DfcLDCs+II16l6WvdfBVJt3hdjWGAQNrW8KqyttBDE8Gs4DvqT6d97BuSmatzjVA90+5vPE+OaOLC4mb52T1eziGn0nIgjUAnTMX0pHdFfg9KGVedAtAcUx53ycIeZpwEbNmBSEzsO2qJM//D9uELOxY4/FWfam+9Nwn2XAwKDJIGxJC7mqRqCwutigXbco/IU3qVWCWslC9jtohVS+1aireDRiuopnMDk4LUnSJu46kQxMYsiB8il4r6RgWfgKw3cPn6kRd6sOkWWrGM6UTgbePnR0L3j8RNFXNGMKyV/aaLG7g=
  app: typescript-express-postgres
