language: node_js
node_js:
  - lts/*
script:
  - nyc npm run test:mocha && nyc report --reporter=text-lcov | coveralls
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: $deploy_api_key_secure
  app: $deploy_app_name
