language: node_js
node_js:
- lts/*
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: U8aoUg812JOWZM9vPBfNFSulxDEC6lctSNmvxmNDiLRUTYYVdI6Y0WgqXMv4lTM/P099b37WZsA650IYgc81C4akdhZT7RqbUORhIe85HMH33+kOyFQLgZQQ+gnQBgjMrLV8MgPZZyEH069jS5wzUPJu7MN3JY4jzCzAN5RrDD7Py3uXySXPjxNK8p11w/GjCBHCdtE0oJEqETrYrrs1frz5bcewoqaT21SpZvRtHXodyloFvffusF9ixrhnrzZ4wahj9LByA9Q050N3lSUxEKy1EPtIWckN+Z6RpNOCTrOQxOkURx2NFpnIZDppI4Hfoq6POEPP7Yd3Y+dmDP40evMf3eSH+aDNuhdQG3Hyk7It/3ElKjcCl60Od5plo3PiuxGZQmH3PHmiOUjOX+XJppptzQdxJ3Qlh5q3LIi7W2yf9lYzGQGExvxi6QcYa2ZIM+2qyjdxbuQ9r54QFwpB6kToGC8lRc5oSZuB+JO4vNbIn8fLJ8fzsDyIeWapJrYPq07pZfqzGjUBbqGBrHW5SFJG/6PpdJZY9LwUhfLYPowNdbHdyJhhK3AGG+elsLaqw0gjZnL/uWX7JSyGWI3yqUHLajUzptc79tqcObP4Ns3KowGIJS0xmgiwYc3WmK2lmA5yyHg+EXdwhBAg9iGSbjwcDloKeg3J9dfAH+/YLgA=
